/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpr.paranavai.armarios.visao;



/**
 *
 * @author teren
 */
public class EditorReservaUI extends javax.swing.JFrame {
   
    /**
     * Creates new form AuthEditorUI
     */
    public EditorReservaUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Pesquisa = new javax.swing.JTextField();
        NumeroArmario = new javax.swing.JTextField();
        ObservacoesArmario = new javax.swing.JTextField();
        DataRetirada = new javax.swing.JTextField();
        HoraRetirada = new javax.swing.JTextField();
        DataDevolucao = new javax.swing.JTextField();
        HoraDevolucao = new javax.swing.JTextField();
        Salvar = new javax.swing.JButton();
        Opcao = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Status = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Retirada = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Devolucao = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Reserva");

        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        Pesquisa.setBackground(new java.awt.Color(255, 255, 255));
        Pesquisa.setForeground(new java.awt.Color(0, 0, 0));
        Pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(Pesquisa);
        Pesquisa.setBounds(170, 70, 300, 24);

        NumeroArmario.setBackground(new java.awt.Color(255, 255, 255));
        NumeroArmario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroArmarioActionPerformed(evt);
            }
        });
        jPanel1.add(NumeroArmario);
        NumeroArmario.setBounds(110, 140, 50, 24);

        ObservacoesArmario.setBackground(new java.awt.Color(255, 255, 255));
        ObservacoesArmario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObservacoesArmarioActionPerformed(evt);
            }
        });
        jPanel1.add(ObservacoesArmario);
        ObservacoesArmario.setBounds(320, 140, 300, 24);

        DataRetirada.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(DataRetirada);
        DataRetirada.setBounds(120, 210, 100, 24);

        HoraRetirada.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(HoraRetirada);
        HoraRetirada.setBounds(290, 210, 120, 24);

        DataDevolucao.setBackground(new java.awt.Color(255, 255, 255));
        DataDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataDevolucaoActionPerformed(evt);
            }
        });
        jPanel1.add(DataDevolucao);
        DataDevolucao.setBounds(120, 310, 100, 24);

        HoraDevolucao.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(HoraDevolucao);
        HoraDevolucao.setBounds(290, 310, 120, 24);

        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });
        jPanel1.add(Salvar);
        Salvar.setBounds(120, 400, 100, 24);

        Opcao.setBackground(new java.awt.Color(255, 255, 255));
        Opcao.setForeground(new java.awt.Color(0, 0, 0));
        Opcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Ra" }));
        Opcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcaoActionPerformed(evt);
            }
        });
        jPanel1.add(Opcao);
        Opcao.setBounds(100, 70, 64, 26);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Estudante");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 50, 60, 16);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Numero");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 120, 50, 16);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Status");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(220, 120, 37, 16);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Obeservacoes");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(420, 120, 90, 16);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Data");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(150, 280, 30, 30);

        Status.setBackground(new java.awt.Color(255, 255, 255));
        Status.setForeground(new java.awt.Color(0, 0, 0));
        Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponivel", "Ocupado" }));
        Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusActionPerformed(evt);
            }
        });
        jPanel1.add(Status);
        Status.setBounds(200, 140, 90, 26);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Data");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(150, 190, 37, 16);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Hora");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(330, 190, 37, 16);

        Retirada.setText("Retirada");
        Retirada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetiradaActionPerformed(evt);
            }
        });
        jPanel1.add(Retirada);
        Retirada.setBounds(120, 240, 59, 24);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Hora");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(340, 280, 50, 30);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Armario");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 140, 50, 30);

        Devolucao.setText("Devolucao");
        Devolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevolucaoActionPerformed(evt);
            }
        });
        jPanel1.add(Devolucao);
        Devolucao.setBounds(120, 340, 70, 24);

        jLabel3.setMinimumSize(new java.awt.Dimension(500, 300));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-70, 0, 700, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");
        jPanel1.getAccessibleContext().setAccessibleDescription("Tela de login");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PesquisaActionPerformed

    private void NumeroArmarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroArmarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroArmarioActionPerformed

    private void ObservacoesArmarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObservacoesArmarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObservacoesArmarioActionPerformed

    private void DataDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataDevolucaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataDevolucaoActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        //String pesquisa = this.Pesquisa.getText();
        //String numero = this.Numero.getText();
        //String retorno = ReservaControlador.verifica(nome, ra);
        //System.out.println(retorno);
        //JOptionPane.showMessageDialog(null,retorno);
        }
    }//GEN-LAST:event_SalvarActionPerformed

    private void RetiradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetiradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RetiradaActionPerformed

    private void DevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevolucaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DevolucaoActionPerformed

    private void StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusActionPerformed

    private void OpcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } 
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorLocalizacaoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorLocalizacaoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorLocalizacaoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorLocalizacaoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new EditorReservaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DataDevolucao;
    private javax.swing.JTextField DataRetirada;
    private javax.swing.JToggleButton Devolucao;
    private javax.swing.JTextField HoraDevolucao;
    private javax.swing.JTextField HoraRetirada;
    private javax.swing.JTextField NumeroArmario;
    private javax.swing.JTextField ObservacoesArmario;
    private javax.swing.JComboBox<String> Opcao;
    private javax.swing.JTextField Pesquisa;
    private javax.swing.JToggleButton Retirada;
    private javax.swing.JButton Salvar;
    private javax.swing.JComboBox<String> Status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
